# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

updateGP <- function(Y, trait, z0, v0, d0, b0, eta0, zeta0, fixv, consb, nsimul, fdegrees, fzeta, hyperparms, target, jumpmin, jumpmax, c, display_progress) {
    .Call(`_PartialNetwork_updateGP`, Y, trait, z0, v0, d0, b0, eta0, zeta0, fixv, consb, nsimul, fdegrees, fzeta, hyperparms, target, jumpmin, jumpmax, c, display_progress)
}

dnetwork1 <- function(T, P, z, d, zeta, N, Metrostart, display_progress) {
    .Call(`_PartialNetwork_dnetwork1`, T, P, z, d, zeta, N, Metrostart, display_progress)
}

dnetwork2 <- function(T, P, z, d, zeta, Xard, Xnonard, iARD, inonARD, M, Metrostart, display_progress) {
    .Call(`_PartialNetwork_dnetwork2`, T, P, z, d, zeta, Xard, Xnonard, iARD, inonARD, M, Metrostart, display_progress)
}

Prob <- function(nu, d, zeta, z) {
    .Call(`_PartialNetwork_Prob`, nu, d, zeta, z)
}

Graph <- function(prob) {
    .Call(`_PartialNetwork_Graph`, prob)
}

instruments1 <- function(dnetwork, X, y, S, pow, expG = FALSE) {
    .Call(`_PartialNetwork_instruments1`, dnetwork, X, y, S, pow, expG)
}

instruments2 <- function(dnetwork, X, S, pow, expG = FALSE) {
    .Call(`_PartialNetwork_instruments2`, dnetwork, X, S, pow, expG)
}

flistGnorm1 <- function(dnetwork, y, Xone, X, M) {
    .Call(`_PartialNetwork_flistGnorm1`, dnetwork, y, Xone, X, M)
}

flistGnorm2 <- function(G, y, Xone, X, M) {
    .Call(`_PartialNetwork_flistGnorm2`, G, y, Xone, X, M)
}

flistGnorm1nc <- function(dnetwork, y, Xone, M) {
    .Call(`_PartialNetwork_flistGnorm1nc`, dnetwork, y, Xone, M)
}

flistGnorm2nc <- function(G, y, Xone, M) {
    .Call(`_PartialNetwork_flistGnorm2nc`, G, y, Xone, M)
}

simG <- function(dnetwork, N, M) {
    .Call(`_PartialNetwork_simG`, dnetwork, N, M)
}

simGnorm <- function(dnetwork, N, M) {
    .Call(`_PartialNetwork_simGnorm`, dnetwork, N, M)
}

peerMCMCnoc_none <- function(y, V, Gnorm, prior, ListIndex, M, N, kbeta, theta0, invsigmatheta, zeta0, invsigma2zeta, a, b, parms0, iteration, target, jumpmin, jumpmax, c, progress) {
    .Call(`_PartialNetwork_peerMCMCnoc_none`, y, V, Gnorm, prior, ListIndex, M, N, kbeta, theta0, invsigmatheta, zeta0, invsigma2zeta, a, b, parms0, iteration, target, jumpmin, jumpmax, c, progress)
}

peerMCMCblocknoc_none <- function(y, V, Gnorm, prior, ListIndex, M, N, kbeta, theta0, invsigmatheta, zeta0, invsigma2zeta, a, b, parms0, iteration, target, jumpmin, jumpmax, c, progress, nupmax) {
    .Call(`_PartialNetwork_peerMCMCblocknoc_none`, y, V, Gnorm, prior, ListIndex, M, N, kbeta, theta0, invsigmatheta, zeta0, invsigma2zeta, a, b, parms0, iteration, target, jumpmin, jumpmax, c, progress, nupmax)
}

peerMCMC_none <- function(y, X, Xone, Gnorm, prior, ListIndex, M, N, kbeta, kgamma, theta0, invsigmatheta, zeta0, invsigma2zeta, a, b, parms0, iteration, target, jumpmin, jumpmax, c, progress) {
    .Call(`_PartialNetwork_peerMCMC_none`, y, X, Xone, Gnorm, prior, ListIndex, M, N, kbeta, kgamma, theta0, invsigmatheta, zeta0, invsigma2zeta, a, b, parms0, iteration, target, jumpmin, jumpmax, c, progress)
}

peerMCMCblock_none <- function(y, X, Xone, Gnorm, prior, ListIndex, M, N, kbeta, kgamma, theta0, invsigmatheta, zeta0, invsigma2zeta, a, b, parms0, iteration, target, jumpmin, jumpmax, c, progress, nupmax) {
    .Call(`_PartialNetwork_peerMCMCblock_none`, y, X, Xone, Gnorm, prior, ListIndex, M, N, kbeta, kgamma, theta0, invsigmatheta, zeta0, invsigma2zeta, a, b, parms0, iteration, target, jumpmin, jumpmax, c, progress, nupmax)
}

peerMCMCnoc_ard <- function(y, V, Gnorm, G0obs, prior, ListIndex, M, N, N1, kbeta, theta0, invsigmatheta, zeta0, invsigma2zeta, a, b, d, zetaard, murho, Vrho, Krho, neighbor, weight, iARD, inonARD, P, parms0, iteration, target, jumpmin, jumpmax, c, type, progress) {
    .Call(`_PartialNetwork_peerMCMCnoc_ard`, y, V, Gnorm, G0obs, prior, ListIndex, M, N, N1, kbeta, theta0, invsigmatheta, zeta0, invsigma2zeta, a, b, d, zetaard, murho, Vrho, Krho, neighbor, weight, iARD, inonARD, P, parms0, iteration, target, jumpmin, jumpmax, c, type, progress)
}

peerMCMCblocknoc_ard <- function(y, V, Gnorm, G0obs, prior, ListIndex, M, N, N1, kbeta, theta0, invsigmatheta, zeta0, invsigma2zeta, a, b, d, zetaard, murho, Vrho, Krho, neighbor, weight, iARD, inonARD, P, parms0, iteration, target, jumpmin, jumpmax, c, type, progress, nupmax) {
    .Call(`_PartialNetwork_peerMCMCblocknoc_ard`, y, V, Gnorm, G0obs, prior, ListIndex, M, N, N1, kbeta, theta0, invsigmatheta, zeta0, invsigma2zeta, a, b, d, zetaard, murho, Vrho, Krho, neighbor, weight, iARD, inonARD, P, parms0, iteration, target, jumpmin, jumpmax, c, type, progress, nupmax)
}

peerMCMC_ard <- function(y, X, Xone, Gnorm, G0obs, prior, ListIndex, M, N, N1, kbeta, kgamma, theta0, invsigmatheta, zeta0, invsigma2zeta, a, b, d, zetaard, murho, Vrho, Krho, neighbor, weight, iARD, inonARD, P, parms0, iteration, target, jumpmin, jumpmax, c, type, progress) {
    .Call(`_PartialNetwork_peerMCMC_ard`, y, X, Xone, Gnorm, G0obs, prior, ListIndex, M, N, N1, kbeta, kgamma, theta0, invsigmatheta, zeta0, invsigma2zeta, a, b, d, zetaard, murho, Vrho, Krho, neighbor, weight, iARD, inonARD, P, parms0, iteration, target, jumpmin, jumpmax, c, type, progress)
}

peerMCMCblock_ard <- function(y, X, Xone, Gnorm, G0obs, prior, ListIndex, M, N, N1, kbeta, kgamma, theta0, invsigmatheta, zeta0, invsigma2zeta, a, b, d, zetaard, murho, Vrho, Krho, neighbor, weight, iARD, inonARD, P, parms0, iteration, target, jumpmin, jumpmax, c, type, progress, nupmax) {
    .Call(`_PartialNetwork_peerMCMCblock_ard`, y, X, Xone, Gnorm, G0obs, prior, ListIndex, M, N, N1, kbeta, kgamma, theta0, invsigmatheta, zeta0, invsigma2zeta, a, b, d, zetaard, murho, Vrho, Krho, neighbor, weight, iARD, inonARD, P, parms0, iteration, target, jumpmin, jumpmax, c, type, progress, nupmax)
}

peerMCMCnoc_pl <- function(y, V, Gnorm, G0obs, prior, ListIndex, M, N, kbeta, theta0, invsigmatheta, zeta0, invsigma2zeta, a, b, weight, dZ, murho, Vrho, Krho, lFdZrho1, lFdZrho0, parms0, iteration, target, jumpmin, jumpmax, c, progress, type, Afixed, G0obsvec) {
    .Call(`_PartialNetwork_peerMCMCnoc_pl`, y, V, Gnorm, G0obs, prior, ListIndex, M, N, kbeta, theta0, invsigmatheta, zeta0, invsigma2zeta, a, b, weight, dZ, murho, Vrho, Krho, lFdZrho1, lFdZrho0, parms0, iteration, target, jumpmin, jumpmax, c, progress, type, Afixed, G0obsvec)
}

peerMCMCblocknoc_pl <- function(y, V, Gnorm, G0obs, prior, ListIndex, M, N, kbeta, theta0, invsigmatheta, zeta0, invsigma2zeta, a, b, weight, dZ, murho, Vrho, Krho, lFdZrho1, lFdZrho0, parms0, iteration, target, jumpmin, jumpmax, c, progress, nupmax, type, Afixed, G0obsvec) {
    .Call(`_PartialNetwork_peerMCMCblocknoc_pl`, y, V, Gnorm, G0obs, prior, ListIndex, M, N, kbeta, theta0, invsigmatheta, zeta0, invsigma2zeta, a, b, weight, dZ, murho, Vrho, Krho, lFdZrho1, lFdZrho0, parms0, iteration, target, jumpmin, jumpmax, c, progress, nupmax, type, Afixed, G0obsvec)
}

peerMCMC_pl <- function(y, X, Xone, Gnorm, G0obs, prior, ListIndex, M, N, kbeta, kgamma, theta0, invsigmatheta, zeta0, invsigma2zeta, a, b, dZ, weight, murho, Vrho, Krho, lFdZrho1, lFdZrho0, parms0, iteration, target, jumpmin, jumpmax, c, progress, type, Afixed, G0obsvec) {
    .Call(`_PartialNetwork_peerMCMC_pl`, y, X, Xone, Gnorm, G0obs, prior, ListIndex, M, N, kbeta, kgamma, theta0, invsigmatheta, zeta0, invsigma2zeta, a, b, dZ, weight, murho, Vrho, Krho, lFdZrho1, lFdZrho0, parms0, iteration, target, jumpmin, jumpmax, c, progress, type, Afixed, G0obsvec)
}

peerMCMCblock_pl <- function(y, X, Xone, Gnorm, G0obs, prior, ListIndex, M, N, kbeta, kgamma, theta0, invsigmatheta, zeta0, invsigma2zeta, a, b, weight, dZ, murho, Vrho, Krho, lFdZrho1, lFdZrho0, parms0, iteration, target, jumpmin, jumpmax, c, progress, nupmax, type, Afixed, G0obsvec) {
    .Call(`_PartialNetwork_peerMCMCblock_pl`, y, X, Xone, Gnorm, G0obs, prior, ListIndex, M, N, kbeta, kgamma, theta0, invsigmatheta, zeta0, invsigma2zeta, a, b, weight, dZ, murho, Vrho, Krho, lFdZrho1, lFdZrho0, parms0, iteration, target, jumpmin, jumpmax, c, progress, nupmax, type, Afixed, G0obsvec)
}

sartpoint <- function(Gnorm, M, N, kbeta, kgamma, y, X, Xone) {
    .Call(`_PartialNetwork_sartpoint`, Gnorm, M, N, kbeta, kgamma, y, X, Xone)
}

sartpointnoc <- function(Gnorm, M, N, kbeta, y, Xone) {
    .Call(`_PartialNetwork_sartpointnoc`, Gnorm, M, N, kbeta, y, Xone)
}

rem_non_fin <- function(net) {
    .Call(`_PartialNetwork_rem_non_fin`, net)
}

fylim <- function(G, talpha, igroup, nvec, ngroup, lambda, n, nthreads) {
    .Call(`_PartialNetwork_fylim`, G, talpha, igroup, nvec, ngroup, lambda, n, nthreads)
}

falbeta0 <- function(R, distr, y, Gy, GX2, V, W, smoother, hN, Kx1, Kx2, ninstr, M, N, Pm, Ncum) {
    .Call(`_PartialNetwork_falbeta0`, R, distr, y, Gy, GX2, V, W, smoother, hN, Kx1, Kx2, ninstr, M, N, Pm, Ncum)
}

fmvzeta0 <- function(alpha, beta, R, distr, y, Gy, GX2, V, W, smoother, hN, Kx1, Kx2, ninstr, M, N, Pm, Ncum) {
    .Call(`_PartialNetwork_fmvzeta0`, alpha, beta, R, distr, y, Gy, GX2, V, W, smoother, hN, Kx1, Kx2, ninstr, M, N, Pm, Ncum)
}

fmvzetaH0 <- function(alpha, beta, R, distr, y, Gy, GX2, V, W, smoother, hN, Kx1, Kx2, ninstr, M, N, Pm, Ncum) {
    .Call(`_PartialNetwork_fmvzetaH0`, alpha, beta, R, distr, y, Gy, GX2, V, W, smoother, hN, Kx1, Kx2, ninstr, M, N, Pm, Ncum)
}

falbeta0nc <- function(R, distr, y, Gy, GX2, V, W, smoother, hN, Kx1, ninstr, M, N, Pm, Ncum) {
    .Call(`_PartialNetwork_falbeta0nc`, R, distr, y, Gy, GX2, V, W, smoother, hN, Kx1, ninstr, M, N, Pm, Ncum)
}

fmvzeta0nc <- function(alpha, beta, R, distr, y, Gy, GX2, V, W, smoother, hN, Kx1, ninstr, M, N, Pm, Ncum) {
    .Call(`_PartialNetwork_fmvzeta0nc`, alpha, beta, R, distr, y, Gy, GX2, V, W, smoother, hN, Kx1, ninstr, M, N, Pm, Ncum)
}

fmvzetaH0nc <- function(alpha, beta, R, distr, y, Gy, GX2, V, W, smoother, hN, Kx1, ninstr, M, N, Pm, Ncum) {
    .Call(`_PartialNetwork_fmvzetaH0nc`, alpha, beta, R, distr, y, Gy, GX2, V, W, smoother, hN, Kx1, ninstr, M, N, Pm, Ncum)
}

falbeta0fe <- function(R, distr, y, Gy, GX2, V, W, smoother, hN, Kx1, Kx2, ninstr, M, N, Pm, Ncum) {
    .Call(`_PartialNetwork_falbeta0fe`, R, distr, y, Gy, GX2, V, W, smoother, hN, Kx1, Kx2, ninstr, M, N, Pm, Ncum)
}

fmvzeta0fe <- function(alpha, beta, R, distr, y, Gy, GX2, V, W, smoother, hN, Kx1, Kx2, ninstr, M, N, Pm, Ncum) {
    .Call(`_PartialNetwork_fmvzeta0fe`, alpha, beta, R, distr, y, Gy, GX2, V, W, smoother, hN, Kx1, Kx2, ninstr, M, N, Pm, Ncum)
}

fmvzetaH0fe <- function(alpha, beta, R, distr, y, Gy, GX2, V, W, smoother, hN, Kx1, Kx2, ninstr, M, N, Pm, Ncum) {
    .Call(`_PartialNetwork_fmvzetaH0fe`, alpha, beta, R, distr, y, Gy, GX2, V, W, smoother, hN, Kx1, Kx2, ninstr, M, N, Pm, Ncum)
}

falbeta0ncfe <- function(R, distr, y, Gy, GX2, V, W, smoother, hN, Kx1, ninstr, M, N, Pm, Ncum) {
    .Call(`_PartialNetwork_falbeta0ncfe`, R, distr, y, Gy, GX2, V, W, smoother, hN, Kx1, ninstr, M, N, Pm, Ncum)
}

fmvzeta0ncfe <- function(alpha, beta, R, distr, y, Gy, GX2, V, W, smoother, hN, Kx1, ninstr, M, N, Pm, Ncum) {
    .Call(`_PartialNetwork_fmvzeta0ncfe`, alpha, beta, R, distr, y, Gy, GX2, V, W, smoother, hN, Kx1, ninstr, M, N, Pm, Ncum)
}

fmvzetaH0ncfe <- function(alpha, beta, R, distr, y, Gy, GX2, V, W, smoother, hN, Kx1, ninstr, M, N, Pm, Ncum) {
    .Call(`_PartialNetwork_fmvzetaH0ncfe`, alpha, beta, R, distr, y, Gy, GX2, V, W, smoother, hN, Kx1, ninstr, M, N, Pm, Ncum)
}

fbeta1 <- function(alpha, Day, Ra, R, S, T, distr, Ilist, y, X1, X2, V, W, smoother, hN, Kx1, Kx2, M, N, Pm, Ncum) {
    .Call(`_PartialNetwork_fbeta1`, alpha, Day, Ra, R, S, T, distr, Ilist, y, X1, X2, V, W, smoother, hN, Kx1, Kx2, M, N, Pm, Ncum)
}

fgmm1 <- function(alpha, R, S, T, distr, Ilist, y, X1, X2, V, W, smoother, hN, Kx1, Kx2, ninstr, M, N, Pm, Ncum) {
    .Call(`_PartialNetwork_fgmm1`, alpha, R, S, T, distr, Ilist, y, X1, X2, V, W, smoother, hN, Kx1, Kx2, ninstr, M, N, Pm, Ncum)
}

fmvzeta1 <- function(alpha, beta, R, S, T, distr, Ilist, y, X1, X2, V, W, smoother, hN, Kx1, Kx2, ninstr, M, N, Pm, Ncum) {
    .Call(`_PartialNetwork_fmvzeta1`, alpha, beta, R, S, T, distr, Ilist, y, X1, X2, V, W, smoother, hN, Kx1, Kx2, ninstr, M, N, Pm, Ncum)
}

fmvzetaH1 <- function(alpha, beta, R, S, T, distr, Ilist, y, X1, X2, V, W, smoother, hN, Kx1, Kx2, ninstr, M, N, Pm, Ncum) {
    .Call(`_PartialNetwork_fmvzetaH1`, alpha, beta, R, S, T, distr, Ilist, y, X1, X2, V, W, smoother, hN, Kx1, Kx2, ninstr, M, N, Pm, Ncum)
}

fbeta1nc <- function(alpha, Day, Ra, R, S, T, distr, Ilist, y, X1, X2, W, smoother, hN, Kx1, M, N, Pm, Ncum) {
    .Call(`_PartialNetwork_fbeta1nc`, alpha, Day, Ra, R, S, T, distr, Ilist, y, X1, X2, W, smoother, hN, Kx1, M, N, Pm, Ncum)
}

fgmm1nc <- function(alpha, R, S, T, distr, Ilist, y, X1, X2, W, smoother, hN, Kx1, ninstr, M, N, Pm, Ncum) {
    .Call(`_PartialNetwork_fgmm1nc`, alpha, R, S, T, distr, Ilist, y, X1, X2, W, smoother, hN, Kx1, ninstr, M, N, Pm, Ncum)
}

fmvzeta1nc <- function(alpha, beta, R, S, T, distr, Ilist, y, X1, X2, W, smoother, hN, Kx1, ninstr, M, N, Pm, Ncum) {
    .Call(`_PartialNetwork_fmvzeta1nc`, alpha, beta, R, S, T, distr, Ilist, y, X1, X2, W, smoother, hN, Kx1, ninstr, M, N, Pm, Ncum)
}

fmvzetaH1nc <- function(alpha, beta, R, S, T, distr, Ilist, y, X1, X2, W, smoother, hN, Kx1, ninstr, M, N, Pm, Ncum) {
    .Call(`_PartialNetwork_fmvzetaH1nc`, alpha, beta, R, S, T, distr, Ilist, y, X1, X2, W, smoother, hN, Kx1, ninstr, M, N, Pm, Ncum)
}

fbeta1fe <- function(alpha, Day, Ra, R, S, T, distr, Ilist, y, X1, X2, V, W, smoother, hN, Kx1, Kx2, M, N, Pm, Ncum) {
    .Call(`_PartialNetwork_fbeta1fe`, alpha, Day, Ra, R, S, T, distr, Ilist, y, X1, X2, V, W, smoother, hN, Kx1, Kx2, M, N, Pm, Ncum)
}

fgmm1fe <- function(alpha, R, S, T, distr, Ilist, y, X1, X2, V, W, smoother, hN, Kx1, Kx2, ninstr, M, N, Pm, Ncum) {
    .Call(`_PartialNetwork_fgmm1fe`, alpha, R, S, T, distr, Ilist, y, X1, X2, V, W, smoother, hN, Kx1, Kx2, ninstr, M, N, Pm, Ncum)
}

fmvzeta1fe <- function(alpha, beta, R, S, T, distr, Ilist, y, X1, X2, V, W, smoother, hN, Kx1, Kx2, ninstr, M, N, Pm, Ncum) {
    .Call(`_PartialNetwork_fmvzeta1fe`, alpha, beta, R, S, T, distr, Ilist, y, X1, X2, V, W, smoother, hN, Kx1, Kx2, ninstr, M, N, Pm, Ncum)
}

fmvzetaH1fe <- function(alpha, beta, R, S, T, distr, Ilist, y, X1, X2, V, W, smoother, hN, Kx1, Kx2, ninstr, M, N, Pm, Ncum) {
    .Call(`_PartialNetwork_fmvzetaH1fe`, alpha, beta, R, S, T, distr, Ilist, y, X1, X2, V, W, smoother, hN, Kx1, Kx2, ninstr, M, N, Pm, Ncum)
}

fbeta1ncfe <- function(alpha, Day, Ra, R, S, T, distr, Ilist, y, X1, X2, W, smoother, hN, Kx1, M, N, Pm, Ncum) {
    .Call(`_PartialNetwork_fbeta1ncfe`, alpha, Day, Ra, R, S, T, distr, Ilist, y, X1, X2, W, smoother, hN, Kx1, M, N, Pm, Ncum)
}

fgmm1ncfe <- function(alpha, R, S, T, distr, Ilist, y, X1, X2, W, smoother, hN, Kx1, ninstr, M, N, Pm, Ncum) {
    .Call(`_PartialNetwork_fgmm1ncfe`, alpha, R, S, T, distr, Ilist, y, X1, X2, W, smoother, hN, Kx1, ninstr, M, N, Pm, Ncum)
}

fmvzeta1ncfe <- function(alpha, beta, R, S, T, distr, Ilist, y, X1, X2, W, smoother, hN, Kx1, ninstr, M, N, Pm, Ncum) {
    .Call(`_PartialNetwork_fmvzeta1ncfe`, alpha, beta, R, S, T, distr, Ilist, y, X1, X2, W, smoother, hN, Kx1, ninstr, M, N, Pm, Ncum)
}

fmvzetaH1ncfe <- function(alpha, beta, R, S, T, distr, Ilist, y, X1, X2, W, smoother, hN, Kx1, ninstr, M, N, Pm, Ncum) {
    .Call(`_PartialNetwork_fmvzetaH1ncfe`, alpha, beta, R, S, T, distr, Ilist, y, X1, X2, W, smoother, hN, Kx1, ninstr, M, N, Pm, Ncum)
}

falbeta2 <- function(R, S, distr, y, X1, X2, Gy, W, smoother, hN, Kx1, Kx2, ninstr, M, N, Pm, Ncum) {
    .Call(`_PartialNetwork_falbeta2`, R, S, distr, y, X1, X2, Gy, W, smoother, hN, Kx1, Kx2, ninstr, M, N, Pm, Ncum)
}

fmvzeta2 <- function(alpha, beta, R, S, distr, y, X1, X2, Gy, W, smoother, hN, Kx1, Kx2, ninstr, M, N, Pm, Ncum) {
    .Call(`_PartialNetwork_fmvzeta2`, alpha, beta, R, S, distr, y, X1, X2, Gy, W, smoother, hN, Kx1, Kx2, ninstr, M, N, Pm, Ncum)
}

fmvzetaH2 <- function(alpha, beta, R, S, distr, y, X1, X2, Gy, W, smoother, hN, Kx1, Kx2, ninstr, M, N, Pm, Ncum) {
    .Call(`_PartialNetwork_fmvzetaH2`, alpha, beta, R, S, distr, y, X1, X2, Gy, W, smoother, hN, Kx1, Kx2, ninstr, M, N, Pm, Ncum)
}

falbeta2nc <- function(R, distr, y, X1, X2, Gy, W, smoother, hN, Kx1, ninstr, M, N, Pm, Ncum) {
    .Call(`_PartialNetwork_falbeta2nc`, R, distr, y, X1, X2, Gy, W, smoother, hN, Kx1, ninstr, M, N, Pm, Ncum)
}

fmvzeta2nc <- function(alpha, beta, R, distr, y, X1, X2, Gy, W, smoother, hN, Kx1, ninstr, M, N, Pm, Ncum) {
    .Call(`_PartialNetwork_fmvzeta2nc`, alpha, beta, R, distr, y, X1, X2, Gy, W, smoother, hN, Kx1, ninstr, M, N, Pm, Ncum)
}

fmvzetaH2nc <- function(alpha, beta, R, distr, y, X1, X2, Gy, W, smoother, hN, Kx1, ninstr, M, N, Pm, Ncum) {
    .Call(`_PartialNetwork_fmvzetaH2nc`, alpha, beta, R, distr, y, X1, X2, Gy, W, smoother, hN, Kx1, ninstr, M, N, Pm, Ncum)
}

falbeta2fe <- function(R, S, distr, y, X1, X2, Gy, W, smoother, hN, Kx1, Kx2, ninstr, M, N, Pm, Ncum) {
    .Call(`_PartialNetwork_falbeta2fe`, R, S, distr, y, X1, X2, Gy, W, smoother, hN, Kx1, Kx2, ninstr, M, N, Pm, Ncum)
}

fmvzeta2fe <- function(alpha, beta, R, S, distr, y, X1, X2, Gy, W, smoother, hN, Kx1, Kx2, ninstr, M, N, Pm, Ncum) {
    .Call(`_PartialNetwork_fmvzeta2fe`, alpha, beta, R, S, distr, y, X1, X2, Gy, W, smoother, hN, Kx1, Kx2, ninstr, M, N, Pm, Ncum)
}

fmvzetaH2fe <- function(alpha, beta, R, S, distr, y, X1, X2, Gy, W, smoother, hN, Kx1, Kx2, ninstr, M, N, Pm, Ncum) {
    .Call(`_PartialNetwork_fmvzetaH2fe`, alpha, beta, R, S, distr, y, X1, X2, Gy, W, smoother, hN, Kx1, Kx2, ninstr, M, N, Pm, Ncum)
}

falbeta2ncfe <- function(R, distr, y, X1, X2, Gy, W, smoother, hN, Kx1, ninstr, M, N, Pm, Ncum) {
    .Call(`_PartialNetwork_falbeta2ncfe`, R, distr, y, X1, X2, Gy, W, smoother, hN, Kx1, ninstr, M, N, Pm, Ncum)
}

fmvzeta2ncfe <- function(alpha, beta, R, distr, y, X1, X2, Gy, W, smoother, hN, Kx1, ninstr, M, N, Pm, Ncum) {
    .Call(`_PartialNetwork_fmvzeta2ncfe`, alpha, beta, R, distr, y, X1, X2, Gy, W, smoother, hN, Kx1, ninstr, M, N, Pm, Ncum)
}

fmvzetaH2ncfe <- function(alpha, beta, R, distr, y, X1, X2, Gy, W, smoother, hN, Kx1, ninstr, M, N, Pm, Ncum) {
    .Call(`_PartialNetwork_fmvzetaH2ncfe`, alpha, beta, R, distr, y, X1, X2, Gy, W, smoother, hN, Kx1, ninstr, M, N, Pm, Ncum)
}

fbeta3 <- function(alpha, Day, Ra, R, S, T, distr, Ilist, y, X1, X2, W, smoother, hN, Kx1, Kx2, M, N, Pm, Ncum) {
    .Call(`_PartialNetwork_fbeta3`, alpha, Day, Ra, R, S, T, distr, Ilist, y, X1, X2, W, smoother, hN, Kx1, Kx2, M, N, Pm, Ncum)
}

fgmm3 <- function(alpha, R, S, T, distr, Ilist, y, X1, X2, W, smoother, hN, Kx1, Kx2, ninstr, M, N, Pm, Ncum) {
    .Call(`_PartialNetwork_fgmm3`, alpha, R, S, T, distr, Ilist, y, X1, X2, W, smoother, hN, Kx1, Kx2, ninstr, M, N, Pm, Ncum)
}

fmvzeta3 <- function(alpha, beta, R, S, T, distr, Ilist, y, X1, X2, W, smoother, hN, Kx1, Kx2, ninstr, M, N, Pm, Ncum) {
    .Call(`_PartialNetwork_fmvzeta3`, alpha, beta, R, S, T, distr, Ilist, y, X1, X2, W, smoother, hN, Kx1, Kx2, ninstr, M, N, Pm, Ncum)
}

fmvzetaH3 <- function(alpha, beta, R, S, T, distr, Ilist, y, X1, X2, W, smoother, hN, Kx1, Kx2, ninstr, M, N, Pm, Ncum) {
    .Call(`_PartialNetwork_fmvzetaH3`, alpha, beta, R, S, T, distr, Ilist, y, X1, X2, W, smoother, hN, Kx1, Kx2, ninstr, M, N, Pm, Ncum)
}

fbeta3nc <- function(alpha, Day, Ra, R, S, T, distr, Ilist, y, X1, X2, W, smoother, hN, Kx1, M, N, Pm, Ncum) {
    .Call(`_PartialNetwork_fbeta3nc`, alpha, Day, Ra, R, S, T, distr, Ilist, y, X1, X2, W, smoother, hN, Kx1, M, N, Pm, Ncum)
}

fgmm3nc <- function(alpha, R, S, T, distr, Ilist, y, X1, X2, W, smoother, hN, Kx1, ninstr, M, N, Pm, Ncum) {
    .Call(`_PartialNetwork_fgmm3nc`, alpha, R, S, T, distr, Ilist, y, X1, X2, W, smoother, hN, Kx1, ninstr, M, N, Pm, Ncum)
}

fmvzeta3nc <- function(alpha, beta, R, S, T, distr, Ilist, y, X1, X2, W, smoother, hN, Kx1, ninstr, M, N, Pm, Ncum) {
    .Call(`_PartialNetwork_fmvzeta3nc`, alpha, beta, R, S, T, distr, Ilist, y, X1, X2, W, smoother, hN, Kx1, ninstr, M, N, Pm, Ncum)
}

fmvzetaH3nc <- function(alpha, beta, R, S, T, distr, Ilist, y, X1, X2, W, smoother, hN, Kx1, ninstr, M, N, Pm, Ncum) {
    .Call(`_PartialNetwork_fmvzetaH3nc`, alpha, beta, R, S, T, distr, Ilist, y, X1, X2, W, smoother, hN, Kx1, ninstr, M, N, Pm, Ncum)
}

fbeta3fe <- function(alpha, Day, Ra, R, S, T, distr, Ilist, y, X1, X2, W, smoother, hN, Kx1, Kx2, M, N, Pm, Ncum) {
    .Call(`_PartialNetwork_fbeta3fe`, alpha, Day, Ra, R, S, T, distr, Ilist, y, X1, X2, W, smoother, hN, Kx1, Kx2, M, N, Pm, Ncum)
}

fgmm3fe <- function(alpha, R, S, T, distr, Ilist, y, X1, X2, W, smoother, hN, Kx1, Kx2, ninstr, M, N, Pm, Ncum) {
    .Call(`_PartialNetwork_fgmm3fe`, alpha, R, S, T, distr, Ilist, y, X1, X2, W, smoother, hN, Kx1, Kx2, ninstr, M, N, Pm, Ncum)
}

fmvzeta3fe <- function(alpha, beta, R, S, T, distr, Ilist, y, X1, X2, W, smoother, hN, Kx1, Kx2, ninstr, M, N, Pm, Ncum) {
    .Call(`_PartialNetwork_fmvzeta3fe`, alpha, beta, R, S, T, distr, Ilist, y, X1, X2, W, smoother, hN, Kx1, Kx2, ninstr, M, N, Pm, Ncum)
}

fmvzetaH3fe <- function(alpha, beta, R, S, T, distr, Ilist, y, X1, X2, W, smoother, hN, Kx1, Kx2, ninstr, M, N, Pm, Ncum) {
    .Call(`_PartialNetwork_fmvzetaH3fe`, alpha, beta, R, S, T, distr, Ilist, y, X1, X2, W, smoother, hN, Kx1, Kx2, ninstr, M, N, Pm, Ncum)
}

fbeta3ncfe <- function(alpha, Day, Ra, R, S, T, distr, Ilist, y, X1, X2, W, smoother, hN, Kx1, M, N, Pm, Ncum) {
    .Call(`_PartialNetwork_fbeta3ncfe`, alpha, Day, Ra, R, S, T, distr, Ilist, y, X1, X2, W, smoother, hN, Kx1, M, N, Pm, Ncum)
}

fgmm3ncfe <- function(alpha, R, S, T, distr, Ilist, y, X1, X2, W, smoother, hN, Kx1, ninstr, M, N, Pm, Ncum) {
    .Call(`_PartialNetwork_fgmm3ncfe`, alpha, R, S, T, distr, Ilist, y, X1, X2, W, smoother, hN, Kx1, ninstr, M, N, Pm, Ncum)
}

fmvzeta3ncfe <- function(alpha, beta, R, S, T, distr, Ilist, y, X1, X2, W, smoother, hN, Kx1, ninstr, M, N, Pm, Ncum) {
    .Call(`_PartialNetwork_fmvzeta3ncfe`, alpha, beta, R, S, T, distr, Ilist, y, X1, X2, W, smoother, hN, Kx1, ninstr, M, N, Pm, Ncum)
}

fmvzetaH3ncfe <- function(alpha, beta, R, S, T, distr, Ilist, y, X1, X2, W, smoother, hN, Kx1, ninstr, M, N, Pm, Ncum) {
    .Call(`_PartialNetwork_fmvzetaH3ncfe`, alpha, beta, R, S, T, distr, Ilist, y, X1, X2, W, smoother, hN, Kx1, ninstr, M, N, Pm, Ncum)
}

fListIndex <- function(prior, G0obs, M, N) {
    .Call(`_PartialNetwork_fListIndex`, prior, G0obs, M, N)
}

fGnormalise <- function(u, M) {
    .Call(`_PartialNetwork_fGnormalise`, u, M)
}

frVtoM <- function(u, N, M) {
    .Call(`_PartialNetwork_frVtoM`, u, N, M)
}

frVtoMnorm <- function(u, N, M) {
    .Call(`_PartialNetwork_frVtoMnorm`, u, N, M)
}

frMtoV <- function(u, N, M) {
    .Call(`_PartialNetwork_frMtoV`, u, N, M)
}

frMceiltoV <- function(u, N, M) {
    .Call(`_PartialNetwork_frMceiltoV`, u, N, M)
}

flspacerho1 <- function(T, P, z, d, zeta, N1, Metrostart) {
    .Call(`_PartialNetwork_flspacerho1`, T, P, z, d, zeta, N1, Metrostart)
}

flspacerho2 <- function(T, P, z, d, zeta, Xard, Xnonard, N1, N2, M, Metrostart) {
    .Call(`_PartialNetwork_flspacerho2`, T, P, z, d, zeta, Xard, Xnonard, N1, N2, M, Metrostart)
}

fdnetARD <- function(zm, num, dm, N1m, N2m, Nm, Pm, zetam, logCpzetam, neighborm, weightm, iARDm, inonARDm) {
    .Call(`_PartialNetwork_fdnetARD`, zm, num, dm, N1m, N2m, Nm, Pm, zetam, logCpzetam, neighborm, weightm, iARDm, inonARDm)
}

rvMFcpp <- function(size, theta) {
    .Call(`_PartialNetwork_rvMFcpp`, size, theta)
}

logCpvMFcpp <- function(p, k) {
    .Call(`_PartialNetwork_logCpvMFcpp`, p, k)
}

dvMFcpp <- function(z, theta, logp = FALSE) {
    .Call(`_PartialNetwork_dvMFcpp`, z, theta, logp)
}

