# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rvMFcpp <- function(size, theta) {
    .Call(`_PartialNetwork_rvMFcpp`, size, theta)
}

logCpvMFcpp <- function(p, k) {
    .Call(`_PartialNetwork_logCpvMFcpp`, p, k)
}

dvMFcpp <- function(z, theta, logp = FALSE) {
    .Call(`_PartialNetwork_dvMFcpp`, z, theta, logp)
}

updateGP <- function(Y, trait, z0, v0, d0, b0, eta0, zeta0, fixv, consb, nsimul, fdegrees, fzeta, hyperparms, target, jumpmin, jumpmax, c, display_progress) {
    .Call(`_PartialNetwork_updateGP`, Y, trait, z0, v0, d0, b0, eta0, zeta0, fixv, consb, nsimul, fdegrees, fzeta, hyperparms, target, jumpmin, jumpmax, c, display_progress)
}

dnetwork1 <- function(T, P, z, d, zeta, traitard, Metrostart, display_progress) {
    .Call(`_PartialNetwork_dnetwork1`, T, P, z, d, zeta, traitard, Metrostart, display_progress)
}

dnetwork2 <- function(T, P, z, d, zeta, traitard, traitnonard, M, Metrostart, display_progress) {
    .Call(`_PartialNetwork_dnetwork2`, T, P, z, d, zeta, traitard, traitnonard, M, Metrostart, display_progress)
}

peerMCMC <- function(y, X, Xone, Gnorm, M, N, kbeta, kgamma, prior, theta0, invsigmatheta, zeta0, invsigma2zeta, a, b, parms0, iteration, target, jumpmin, jumpmax, c, progress) {
    .Call(`_PartialNetwork_peerMCMC`, y, X, Xone, Gnorm, M, N, kbeta, kgamma, prior, theta0, invsigmatheta, zeta0, invsigma2zeta, a, b, parms0, iteration, target, jumpmin, jumpmax, c, progress)
}

peerMCMCblock <- function(y, X, Xone, Gnorm, M, N, kbeta, kgamma, prior, theta0, invsigmatheta, zeta0, invsigma2zeta, a, b, parms0, iteration, target, jumpmin, jumpmax, c, nupmax, progress) {
    .Call(`_PartialNetwork_peerMCMCblock`, y, X, Xone, Gnorm, M, N, kbeta, kgamma, prior, theta0, invsigmatheta, zeta0, invsigma2zeta, a, b, parms0, iteration, target, jumpmin, jumpmax, c, nupmax, progress)
}

sartpoint <- function(Gnorm, M, N, kbeta, kgamma, y, X, Xone) {
    .Call(`_PartialNetwork_sartpoint`, Gnorm, M, N, kbeta, kgamma, y, X, Xone)
}

Prob <- function(nu, d, zeta, z) {
    .Call(`_PartialNetwork_Prob`, nu, d, zeta, z)
}

Graph <- function(prob) {
    .Call(`_PartialNetwork_Graph`, prob)
}

instruments1 <- function(dnetwork, X, y, S, pow) {
    .Call(`_PartialNetwork_instruments1`, dnetwork, X, y, S, pow)
}

instruments2 <- function(dnetwork, X, S, pow) {
    .Call(`_PartialNetwork_instruments2`, dnetwork, X, S, pow)
}

flistGnorm1 <- function(dnetwork, y, Xone, X, M) {
    .Call(`_PartialNetwork_flistGnorm1`, dnetwork, y, Xone, X, M)
}

flistGnorm2 <- function(dnetwork, Gnorm, y, Xone, X, M) {
    .Call(`_PartialNetwork_flistGnorm2`, dnetwork, Gnorm, y, Xone, X, M)
}

flistGnorm1nc <- function(dnetwork, y, Xone, M) {
    .Call(`_PartialNetwork_flistGnorm1nc`, dnetwork, y, Xone, M)
}

flistGnorm2nc <- function(dnetwork, Gnorm, y, Xone, M) {
    .Call(`_PartialNetwork_flistGnorm2nc`, dnetwork, Gnorm, y, Xone, M)
}

