# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rvMF <- function(size, theta) {
    .Call(`_PartialNetwork_rvMF`, size, theta)
}

logCpvMF <- function(p, k) {
    .Call(`_PartialNetwork_logCpvMF`, p, k)
}

dvMF <- function(z, theta, logp = FALSE) {
    .Call(`_PartialNetwork_dvMF`, z, theta, logp)
}

updateGP <- function(Y, trait, start, fixv, consb, nsimul = 10000, fdegrees = FALSE, fzeta = FALSE, hyperparms = as.numeric( c(0,1,0,1,5,0.5,1,1)), target = as.numeric( c(1,1,1,1,1)*0.44), jumpmin = as.numeric( c(1,1,1,1,1)*1e-12), jumpmax = as.numeric( c(10,1,1,1,1)*20), c = 0.6) {
    .Call(`_PartialNetwork_updateGP`, Y, trait, start, fixv, consb, nsimul, fdegrees, fzeta, hyperparms, target, jumpmin, jumpmax, c)
}

dnetwork <- function(Gparms, traitard, traitnonard = NULL, m = NULL, metrostart = NULL) {
    .Call(`_PartialNetwork_dnetwork`, Gparms, traitard, traitnonard, m, metrostart)
}

Prob <- function(nu, d, zeta, z) {
    .Call(`_PartialNetwork_Prob`, nu, d, zeta, z)
}

Graph <- function(prob) {
    .Call(`_PartialNetwork_Graph`, prob)
}

invmodij <- function(invM, i, j, eps_) {
    .Call(`_PartialNetwork_invmodij`, invM, i, j, eps_)
}

invmodijk <- function(invM, i, j, k, eps_1, eps_2) {
    .Call(`_PartialNetwork_invmodijk`, invM, i, j, k, eps_1, eps_2)
}

detmodij <- function(detM, invM, i, j, eps_) {
    .Call(`_PartialNetwork_detmodij`, detM, invM, i, j, eps_)
}

detmodijk <- function(detM, invM, i, j, k, eps_1, eps_2) {
    .Call(`_PartialNetwork_detmodijk`, detM, invM, i, j, k, eps_1, eps_2)
}

peerMCMC <- function(y, X, parms0, hyperparms, iteration = 1L, intercept = TRUE, target = 0.44, jumpmin = 1e-12, jumpmax = 100, c = 0.6) {
    .Call(`_PartialNetwork_peerMCMC`, y, X, parms0, hyperparms, iteration, intercept, target, jumpmin, jumpmax, c)
}

sartpoint <- function(prior, y, X, intercept = TRUE) {
    .Call(`_PartialNetwork_sartpoint`, prior, y, X, intercept)
}

instruments <- function(distr, X, y = NULL, S = 2L, pow = 1L) {
    .Call(`_PartialNetwork_instruments`, distr, X, y, S, pow)
}

